# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 211bd48b170fb61e57b84eb963e19e8396fe5dad39e2039c32422655390dbde4f008cb536ecc796089510178d9979708f786fe4085d9a72dac0ed93b470384f6

test:
  secret_key_base: bd1ca13faa2a45a3156c436e3a5088026e4d2dfa8c7d553ac4e2cc752fdfc86036a5d248ec1e02e98d425c758cb3514cd4376042370dc98ab5dc9ce1be44c579

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
