# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

products = [
    { name:"Acerola",
      calories: 32,
      protein: 0.4,
      fat: 0.3,
      carbo: 7.7},
    { name:"Agrest",
      calories: 44,
      protein: 0.9,
      fat: 0.6,
      carbo: 10.2},
    { name:"Ananas",
      calories: 50,
      protein: 0.5,
      fat: 0.1,
      carbo: 13.1},
    { name:"Arbuz",
      calories: 30,
      protein: 0.6,
      fat: 0.2,
      carbo: 7.6},
    { name:"Awokado",
      calories: 160,
      protein: 2,
      fat: 15,
      carbo: 8.5},
    { name:"Bakłażan",
      calories: 25,
      protein: 1,
      fat: 0.2,
      carbo: 5.9},
    { name:"Banan",
      calories: 89,
      protein: 1.1,
      fat: 0.3,
      carbo: 22.8},
    { name:"Borówki",
      calories: 57,
      protein: 0.7,
      fat: 0.3,
      carbo: 14},
    { name:"Brokuły",
      calories: 34,
      protein: 2.8,
      fat: 0.4,
      carbo: 6.6},
    { name:"Brukselka",
      calories: 43,
      protein: 3.4,
      fat: 0.3,
      carbo: 9},
    { name:"Brzoskwinie",
      calories: 39,
      protein: 0.9,
      fat: 0.3,
      carbo: 9.5},
    { name:"Bułeczka mleczna",
      calories: 345,
      protein: 9,
      fat: 10,
      carbo: 54},
    { name:"Bułka tarta",
      calories: 383,
      protein: 14,
      fat: 5.5,
      carbo: 68},
    { name:"Buraki",
      calories: 43,
      protein: 1.6,
      fat: 0.2,
      carbo: 9.6},
    { name:"Cebula",
      calories: 40,
      protein: 1.1,
      fat: 0.1,
      carbo: 9.3},
    { name:"Chleb pszenny",
      calories: 266,
      protein: 11,
      fat: 3.6,
      carbo: 48},
    { name:"Chleb pumpernikiel",
      calories: 250,
      protein: 8.7,
      fat: 3.1,
      carbo: 47.5},
    { name:"Chleb z mški kukurydzianej",
      calories: 314,
      protein: 7.2,
      fat: 10,
      carbo: 48},
    { name:"Chleb z mški razowej",
      calories: 278,
      protein: 8.4,
      fat: 5.4,
      carbo: 51},
    { name:"Chleb żytni",
      calories: 258,
      protein: 8.5,
      fat: 3.3,
      carbo: 48},
    { name:"Chorizo",
      calories: 455,
      protein: 24,
      fat: 38,
      carbo: 1.9},
    { name:"Ciecierzyca",
      calories: 364,
      protein: 19,
      fat: 6,
      carbo: 61},
    { name:"Cukinia",
      calories: 21,
      protein: 2.7,
      fat: 0.4,
      carbo: 3.1},
    { name:"Cykoria",
      calories: 17,
      protein: 0.9,
      fat: 0.2,
      carbo: 4},
    { name:"Cytryny",
      calories: 29,
      protein: 1.1,
      fat: 0.3,
      carbo: 9.3},
    { name:"Czarna porzeczka",
      calories: 63,
      protein: 1.4,
      fat: 0.4,
      carbo: 15.4},
    { name:"Czerwona porzeczka",
      calories: 56,
      protein: 1.4,
      fat: 0.2,
      carbo: 14},
    { name:"Czosnek",
      calories: 149,
      protein: 6.4,
      fat: 0.5,
      carbo: 33.1},
    { name:"Dorsz atlantycki",
      calories: 82,
      protein: 17.8,
      fat: 0.7,
      carbo: 0},
    { name:"Dynia",
      calories: 26,
      protein: 1,
      fat: 0.1,
      carbo: 6.5},
    { name:"Dziki ryż",
      calories: 357,
      protein: 14.7,
      fat: 1.1,
      carbo: 74.9},
    { name:"Fasola biała",
      calories: 333,
      protein: 23.6,
      fat: 0.9,
      carbo: 60},
    { name:"Fasola czerwona",
      calories: 337,
      protein: 22.5,
      fat: 1.1,
      carbo: 61.3},
    { name:"Fasola mung",
      calories: 30,
      protein: 3,
      fat: 0.2,
      carbo: 5.9},
    { name:"Fasola żółta",
      calories: 345,
      protein: 22,
      fat: 2.6,
      carbo: 60.7},
    { name:"Figi",
      calories: 74,
      protein: 0.8,
      fat: 0.3,
      carbo: 19.2},
    { name:"Frankfurterka",
      calories: 290,
      protein: 10,
      fat: 26,
      carbo: 4.2},
    { name:"Gę",
      calories: 161,
      protein: 22.8,
      fat: 7.1,
      carbo: 0},
    { name:"Granaty",
      calories: 83,
      protein: 1.7,
      fat: 1.2,
      carbo: 18.7},
    { name:"Grejpfrut biały",
      calories: 33,
      protein: 0.7,
      fat: 0.1,
      carbo: 8.4},
    { name:"Grejpfrut różowy",
      calories: 42,
      protein: 0.8,
      fat: 0.1,
      carbo: 10.7},
    { name:"Groch",
      calories: 124,
      protein: 8.8,
      fat: 0.7,
      carbo: 27.1},
    { name:"Gruszki",
      calories: 57,
      protein: 0.4,
      fat: 0.1,
      carbo: 15.2},
    { name:"Guawa",
      calories: 68,
      protein: 2.6,
      fat: 0.3,
      carbo: 14.3},
    { name:"Halibut",
      calories: 186,
      protein: 14,
      fat: 14,
      carbo: 0},
    { name:"Imbir",
      calories: 80,
      protein: 1.8,
      fat: 0.8,
      carbo: 17.8},
    { name:"Indyk",
      calories: 148,
      protein: 19.7,
      fat: 10,
      carbo: 0},
    { name:"Indyk pier",
      calories: 104,
      protein: 17,
      fat: 1.7,
      carbo: 4.2},
    { name:"Jabłko",
      calories: 52,
      protein: 0.3,
      fat: 0.1,
      carbo: 13.8},
    { name:"Jagody",
      calories: 57,
      protein: 0.7,
      fat: 0.6,
      carbo: 14.5},
    { name:"Jajko",
      calories: 143,
      protein: 12.6,
      fat: 9.9,
      carbo: 0.7},
    { name:"Jeżyny",
      calories: 43,
      protein: 1.4,
      fat: 0.5,
      carbo: 9.6},
    { name:"Jęczmień",
      calories: 352,
      protein: 9.9,
      fat: 2.3,
      carbo: 77.7},
    { name:"Kaczka",
      calories: 123,
      protein: 20,
      fat: 4.3,
      carbo: 0},
    { name:"Kalafior",
      calories: 25,
      protein: 1.9,
      fat: 0.3,
      carbo: 5},
    { name:"Kalafior zielony",
      calories: 31,
      protein: 3,
      fat: 0.3,
      carbo: 6.1},
    { name:"Kalarepa",
      calories: 27,
      protein: 1.7,
      fat: 0.1,
      carbo: 6.2},
    { name:"Kapusta",
      calories: 25,
      protein: 1.3,
      fat: 0.1,
      carbo: 5.8},
    { name:"Kapusta czerwona",
      calories: 31,
      protein: 1.4,
      fat: 0.2,
      carbo: 7.4},
    { name:"Karambola",
      calories: 31,
      protein: 1,
      fat: 0.4,
      carbo: 6.7},
    { name:"Karczoch",
      calories: 101,
      protein: 1.9,
      fat: 7.8,
      carbo: 3.9},
    { name:"Karczochy",
      calories: 47,
      protein: 3.3,
      fat: 0.2,
      carbo: 10.5},
    { name:"Karp",
      calories: 127,
      protein: 17.8,
      fat: 5.6,
      carbo: 0},
    { name:"Kaszanka",
      calories: 379,
      protein: 15,
      fat: 35,
      carbo: 1.3},
    { name:"Kasztany",
      calories: 213,
      protein: 2.4,
      fat: 2.3,
      carbo: 45.5},
    { name:"Keczup",
      calories: 97,
      protein: 1.7,
      fat: 0.3,
      carbo: 25},
    { name:"Kiwi",
      calories: 61,
      protein: 1.1,
      fat: 0.5,
      carbo: 14.7},
    { name:"Klementynka",
      calories: 47,
      protein: 0.9,
      fat: 0.2,
      carbo: 12},
    { name:"Kminek",
      calories: 333,
      protein: 19.8,
      fat: 15,
      carbo: 49.9},
    { name:"Koperek",
      calories: 43,
      protein: 3.5,
      fat: 1.1,
      carbo: 7},
    { name:"Koza",
      calories: 109,
      protein: 20.6,
      fat: 2.3,
      carbo: 0},
    { name:"Krewetki",
      calories: 106,
      protein: 20,
      fat: 1.7,
      carbo: 0.9},
    { name:"Królik",
      calories: 114,
      protein: 21.8,
      fat: 2.3,
      carbo: 0},
    { name:"Kukurydza",
      calories: 86,
      protein: 3.3,
      fat: 1.2,
      carbo: 18.7},
    { name:"Kurczak",
      calories: 213,
      protein: 18,
      fat: 15,
      carbo: 0.1},
    { name:"Kurczak pier",
      calories: 172,
      protein: 21,
      fat: 9.3,
      carbo: 0},
    { name:"Kurczak podroby",
      calories: 124,
      protein: 18,
      fat: 4.5,
      carbo: 1.8},
    { name:"Kurczak podudzie",
      calories: 161,
      protein: 19,
      fat: 8.7,
      carbo: 0},
    { name:"Kurczak skrzydło",
      calories: 126,
      protein: 22,
      fat: 3.5,
      carbo: 0},
    { name:"Kurczak udo",
      calories: 119,
      protein: 20,
      fat: 3.9,
      carbo: 0},
    { name:"Kurki",
      calories: 38,
      protein: 1.5,
      fat: 0.5,
      carbo: 6.9},
    { name:"Liczi",
      calories: 66,
      protein: 0.8,
      fat: 0.4,
      carbo: 16.5},
    { name:"Limonki",
      calories: 30,
      protein: 0.7,
      fat: 0.2,
      carbo: 10.5},
    { name:"Łopatka ",
      calories: 148,
      protein: 20,
      fat: 7.1,
      carbo: 0},
    { name:"Łoso surowy",
      calories: 116,
      protein: 20,
      fat: 3.5,
      carbo: 0},
    { name:"Majonez",
      calories: 333,
      protein: 0.9,
      fat: 33,
      carbo: 6.7},
    { name:"Majonez Light",
      calories: 324,
      protein: 0.9,
      fat: 33,
      carbo: 8.2},
    { name:"Makrela",
      calories: 105,
      protein: 20.3,
      fat: 2,
      carbo: 0},
    { name:"Maliny",
      calories: 52,
      protein: 1.2,
      fat: 0.2,
      carbo: 11.9},
    { name:"Mandarynki",
      calories: 53,
      protein: 0.8,
      fat: 0.2,
      carbo: 13.3},
    { name:"Mango",
      calories: 60,
      protein: 0.8,
      fat: 0.3,
      carbo: 15},
    { name:"Marchew",
      calories: 41,
      protein: 0.9,
      fat: 0.2,
      carbo: 9.6},
    { name:"Marchew baby",
      calories: 35,
      protein: 0.6,
      fat: 0.2,
      carbo: 8.2},
    { name:"Margaryna",
      calories: 714,
      protein: 0.5,
      fat: 80,
      carbo: 0.5},
    { name:"Masło bez soli",
      calories: 717,
      protein: 0.9,
      fat: 81,
      carbo: 0.6},
    { name:"Masło z solš",
      calories: 717,
      protein: 0.9,
      fat: 81,
      carbo: 0.6},
    { name:"Mška pszenna typ 500",
      calories: 343,
      protein: 10.1,
      fat: 1.2,
      carbo: 74},
    { name:"Mška sojowa",
      calories: 434,
      protein: 37.8,
      fat: 1.5,
      carbo: 31.9},
    { name:"Melon Cantalupa",
      calories: 34,
      protein: 0.8,
      fat: 0.2,
      carbo: 8.2},
    { name:"Melon Casaba",
      calories: 28,
      protein: 1.1,
      fat: 0.1,
      carbo: 6.6},
    { name:"Melon miodowy",
      calories: 36,
      protein: 0.5,
      fat: 0.1,
      carbo: 9.1},
    { name:"Mięso mielone wieprzowe",
      calories: 263,
      protein: 17,
      fat: 21,
      carbo: 0},
    { name:"Mięso mielone z szynki",
      calories: 26,
      protein: 16,
      fat: 21,
      carbo: 1.8},
    { name:"Migdały",
      calories: 575,
      protein: 21,
      fat: 49,
      carbo: 22},
    { name:"Mintaj",
      calories: 92,
      protein: 19.4,
      fat: 0.6,
      carbo: 0},
    { name:"Morele",
      calories: 48,
      protein: 1.4,
      fat: 0.4,
      carbo: 11.1},
    { name:"Mortadela",
      calories: 196,
      protein: 12,
      fat: 14.7,
      carbo: 3.9},
    { name:"Nektarynki",
      calories: 44,
      protein: 1.1,
      fat: 0.3,
      carbo: 10.6},
    { name:"Ogórek",
      calories: 12,
      protein: 0.6,
      fat: 0.1,
      carbo: 2.2},
    { name:"Okoń",
      calories: 91,
      protein: 19.4,
      fat: 0.9,
      carbo: 0},
    { name:"Olej kokosowy",
      calories: 862,
      protein: 0,
      fat: 100,
      carbo: 0},
    { name:"Olej rzepakowy",
      calories: 884,
      protein: 0,
      fat: 100,
      carbo: 0},
    { name:"Oliwa z oliwek",
      calories: 884,
      protein: 0,
      fat: 100,
      carbo: 0},
    { name:"Oliwki",
      calories: 145,
      protein: 1,
      fat: 15,
      carbo: 3.8},
    { name:"Orzechy brazylijskie",
      calories: 710,
      protein: 9.5,
      fat: 74,
      carbo: 14},
    { name:"Orzechy laskowe",
      calories: 628,
      protein: 15,
      fat: 61,
      carbo: 17},
    { name:"Orzechy makadamia",
      calories: 718,
      protein: 7.9,
      fat: 76,
      carbo: 13.8},
    { name:"Orzechy nerkowca",
      calories: 553,
      protein: 18.2,
      fat: 43.8,
      carbo: 30.2},
    { name:"Orzeszki ziemne",
      calories: 567,
      protein: 25.8,
      fat: 49,
      carbo: 16.1},
    { name:"Otręby owsiane",
      calories: 246,
      protein: 17.3,
      fat: 7,
      carbo: 66.2},
    { name:"Papryczka Chili czerwona",
      calories: 40,
      protein: 1.9,
      fat: 0.4,
      carbo: 8.8},
    { name:"Papryczka Chili zielona",
      calories: 40,
      protein: 2,
      fat: 0.2,
      carbo: 9.5},
    { name:"Papryka czerwona",
      calories: 31,
      protein: 1,
      fat: 0.3,
      carbo: 6},
    { name:"Papryka jalapeno",
      calories: 29,
      protein: 0.9,
      fat: 0.9,
      carbo: 6.5},
    { name:"Papryka zielona",
      calories: 20,
      protein: 0.9,
      fat: 0.2,
      carbo: 4.6},
    { name:"Papryka żółta",
      calories: 27,
      protein: 1,
      fat: 0.2,
      carbo: 6.3},
    { name:"Pędy bambusa",
      calories: 27,
      protein: 2.6,
      fat: 0.3,
      carbo: 5.2},
    { name:"Pieczarki",
      calories: 31,
      protein: 2.3,
      fat: 0.5,
      carbo: 3.2},
    { name:"Pietruszka",
      calories: 36,
      protein: 3,
      fat: 0.8,
      carbo: 6.3},
    { name:"Pistacje",
      calories: 560,
      protein: 20.2,
      fat: 45,
      carbo: 27.2},
    { name:"Polędwiczka wieprzowa",
      calories: 109,
      protein: 21,
      fat: 2.2,
      carbo: 0},
    { name:"Pomarańcza",
      calories: 63,
      protein: 1.3,
      fat: 0.2,
      carbo: 15.5},
    { name:"Pomelo",
      calories: 38,
      protein: 0.8,
      fat: 9.6,
      carbo: 0},
    { name:"Pomidor czerwony",
      calories: 18,
      protein: 0.9,
      fat: 0.2,
      carbo: 3.9},
    { name:"Pomidor pomarańczowy",
      calories: 16,
      protein: 1.2,
      fat: 0.2,
      carbo: 3.2},
    { name:"Pomidor zielony",
      calories: 23,
      protein: 1.2,
      fat: 0.2,
      carbo: 5.1},
    { name:"Pomidor żółty",
      calories: 15,
      protein: 1,
      fat: 0.3,
      carbo: 3},
    { name:"Por",
      calories: 61,
      protein: 1.5,
      fat: 0.3,
      carbo: 14.2},
    { name:"Pstršg",
      calories: 148,
      protein: 20.8,
      fat: 6.6,
      carbo: 0},
    { name:"Pstršg tęczowy",
      calories: 141,
      protein: 19.9,
      fat: 3.5,
      carbo: 0},
    { name:"Rabarbar",
      calories: 21,
      protein: 0.9,
      fat: 0.5,
      carbo: 4.5},
    { name:"Radicchio",
      calories: 23,
      protein: 1.4,
      fat: 4.5,
      carbo: 0.3},
    { name:"Rodzynki",
      calories: 299,
      protein: 3.1,
      fat: 0.5,
      carbo: 79},
    { name:"Rukola",
      calories: 25,
      protein: 2.6,
      fat: 0.7,
      carbo: 3.7},
    { name:"Ryba malana",
      calories: 195,
      protein: 13,
      fat: 15,
      carbo: 0},
    { name:"Ryż biały długoziarnisty",
      calories: 365,
      protein: 7.1,
      fat: 0.7,
      carbo: 80},
    { name:"Ryż bršzowy długoziarnisty",
      calories: 367,
      protein: 7.5,
      fat: 2.2,
      carbo: 76.3},
    { name:"Ryż paraboiled",
      calories: 374,
      protein: 8,
      fat: 1,
      carbo: 80},
    { name:"Rzepa",
      calories: 32,
      protein: 1.5,
      fat: 0.5,
      carbo: 7.1},
    { name:"Rzeżucha",
      calories: 11,
      protein: 2.3,
      fat: 0.7,
      carbo: 1.3},
    { name:"Rzodkiewka",
      calories: 16,
      protein: 0.7,
      fat: 0.1,
      carbo: 3.4},
    { name:"Salceson",
      calories: 157,
      protein: 14,
      fat: 11,
      carbo: 0},
    { name:"Sałata lodowa",
      calories: 14,
      protein: 0.9,
      fat: 0.1,
      carbo: 3},
    { name:"Sałata masłowa",
      calories: 13,
      protein: 1.4,
      fat: 0.2,
      carbo: 2.2},
    { name:"Sałata zielona",
      calories: 15,
      protein: 1.4,
      fat: 0.2,
      carbo: 2.8},
    { name:"Schab",
      calories: 143,
      protein: 21,
      fat: 5.7,
      carbo: 0},
    { name:"Seler korzeniowy",
      calories: 42,
      protein: 1.5,
      fat: 0.3,
      carbo: 9.2},
    { name:"Seler naciowy",
      calories: 16,
      protein: 0.7,
      fat: 0.2,
      carbo: 3},
    { name:"Ser Brie",
      calories: 334,
      protein: 21,
      fat: 28,
      carbo: 0.5},
    { name:"Ser Camembert",
      calories: 300,
      protein: 20,
      fat: 24,
      carbo: 0.5},
    { name:"Ser Cheddar",
      calories: 239,
      protein: 17,
      fat: 14,
      carbo: 12},
    { name:"Ser Edam",
      calories: 357,
      protein: 25,
      fat: 28,
      carbo: 1.4},
    { name:"Ser feta",
      calories: 357,
      protein: 25,
      fat: 27,
      carbo: 2.2},
    { name:"Ser Gouda",
      calories: 356,
      protein: 24.9,
      fat: 27.4,
      carbo: 2.2},
    { name:"Ser kozi",
      calories: 268,
      protein: 19,
      fat: 21,
      carbo: 0.9},
    { name:"Ser Mozarella",
      calories: 254,
      protein: 24,
      fat: 16,
      carbo: 2.8},
    { name:"Ser Parmezan",
      calories: 415,
      protein: 38,
      fat: 27,
      carbo: 3.4},
    { name:"Ser Ricotta",
      calories: 174,
      protein: 11,
      fat: 13,
      carbo: 3},
    { name:"Ser topiony",
      calories: 342,
      protein: 5.9,
      fat: 34,
      carbo: 4.1},
    { name:"Serek wiejski",
      calories: 86,
      protein: 12,
      fat: 2.5,
      carbo: 3.7},
    { name:"Skórka pomarańczowa",
      calories: 97,
      protein: 1.5,
      fat: 0.2,
      carbo: 25},
    { name:"Skórka z cytryny",
      calories: 47,
      protein: 1.5,
      fat: 0.3,
      carbo: 16},
    { name:"Słodkie ziemniaki",
      calories: 86,
      protein: 1.6,
      fat: 0.2,
      carbo: 20.1},
    { name:"Soczewica",
      calories: 352,
      protein: 24.6,
      fat: 1.1,
      carbo: 63.4},
    { name:"Soja",
      calories: 147,
      protein: 13,
      fat: 6.8,
      carbo: 11.1},
    { name:"Sok pomarańczowy",
      calories: 45,
      protein: 0.7,
      fat: 0.2,
      carbo: 10.4},
    { name:"Sok z aceroli",
      calories: 23,
      protein: 0.4,
      fat: 0.3,
      carbo: 4.8},
    { name:"Sok z białego grejfjuta",
      calories: 39,
      protein: 0.5,
      fat: 0.1,
      carbo: 9.2},
    { name:"Sok z cytryny",
      calories: 22,
      protein: 0.4,
      fat: 0,
      carbo: 6.9},
    { name:"Sok z limonki",
      calories: 25,
      protein: 0.4,
      fat: 0.6,
      carbo: 8.4},
    { name:"Sok z mandarynki",
      calories: 43,
      protein: 0.5,
      fat: 0.2,
      carbo: 10.1},
    { name:"Sok z różowego grejfjuta",
      calories: 39,
      protein: 0.5,
      fat: 0.1,
      carbo: 9.2},
    { name:"Sok żurawinowy",
      calories: 46,
      protein: 0.4,
      fat: 12,
      carbo: 0.1},
    { name:"Sum",
      calories: 95,
      protein: 16,
      fat: 2.8,
      carbo: 0},
    { name:"Szalotka",
      calories: 72,
      protein: 2.5,
      fat: 0.1,
      carbo: 16.8},
    { name:"Szczupak",
      calories: 88,
      protein: 19.3,
      fat: 0.7,
      carbo: 0},
    { name:"Szczypiorek",
      calories: 30,
      protein: 3.3,
      fat: 0.7,
      carbo: 4.4},
    { name:"Szparagi",
      calories: 20,
      protein: 2.2,
      fat: 0.2,
      carbo: 3.9},
    { name:"Szpinak",
      calories: 23,
      protein: 2.9,
      fat: 0.4,
      carbo: 3.6},
    { name:"Szynka szwarcwaldzka",
      calories: 205,
      protein: 21,
      fat: 13,
      carbo: 1},
    { name:"led",
      calories: 158,
      protein: 18,
      fat: 9,
      carbo: 0},
    { name:"liwki",
      calories: 46,
      protein: 0.7,
      fat: 0.3,
      carbo: 11.4},
    { name:"mietana",
      calories: 135,
      protein: 2.9,
      fat: 12,
      carbo: 4.3},
    { name:"Tilapia",
      calories: 96,
      protein: 20.1,
      fat: 1.7,
      carbo: 0},
    { name:"Trawa cytrynowa",
      calories: 99,
      protein: 1.8,
      fat: 0,
      carbo: 25.3},
    { name:"Troć",
      calories: 104,
      protein: 16.7,
      fat: 3.6,
      carbo: 0},
    { name:"Truskawki",
      calories: 32,
      protein: 0.7,
      fat: 0.3,
      carbo: 7.7},
    { name:"Tuńczyk",
      calories: 144,
      protein: 23.3,
      fat: 4.9,
      carbo: 0},
    { name:"Wasabi",
      calories: 109,
      protein: 4.8,
      fat: 0.6,
      carbo: 23.5},
    { name:"Węgorz",
      calories: 184,
      protein: 18.4,
      fat: 24,
      carbo: 0},
    { name:"Winogrono czerwone",
      calories: 69,
      protein: 0.7,
      fat: 0.2,
      carbo: 18.1},
    { name:"Winogrono zielone",
      calories: 67,
      protein: 0.6,
      fat: 0.2,
      carbo: 17.2},
    { name:"Winie",
      calories: 50,
      protein: 1,
      fat: 0.3,
      carbo: 12.2},
    { name:"Ziemniaki białe",
      calories: 58,
      protein: 2.6,
      fat: 0.1,
      carbo: 12.4},
    { name:"Żółtko jajka",
      calories: 317,
      protein: 16,
      fat: 27,
      carbo: 3.6},
    { name:"Żurawina",
      calories: 46,
      protein: 0.5,
      fat: 0.1,
      carbo: 12}
]

products.each do |product|
  Product.create(:name => product[:name], :calories => product[:calories], :proteins => product[:protein],
                  :lipids => product[:fat], :carbs => product[:carbo] )
end

